#! /usr/bin/env bash

#backup to
#PREFIX="$( dirname "${BASH_SOURCE[0]}" )"
PREFIX=`pwd`

#backup from
backup_list=(
    "/home/$USER/.bashrc"
    "/home/$USER/.zshrc" 
    "/home/$USER/.vimrc"
    "/home/$USER/.zshenv" 
    "/home/$USER/.zshrc.pre-oh-my-zsh"
    "/home/$USER/.config/nvim/" 
    "/home/$USER/.vim/autoload/plug.vim" )

msg=$'usage: '$0$'  <command>\n
    command:\n
        backup\n 
        recovery'
if [[ $# != 1 ]]; then
    echo $msg
    exit 1
fi

case $1 in
    backup)
        for item in ${backup_list[@]} ;do
            echo backup $item to "$PREFIX"$item
            cp -r --parents $item  $PREFIX
        done
        ;;
    recovery)
        for item in ${backup_list[@]} ;do
            echo recovery $item from $PREFIX$item
            cp -ri "$PREFIX""$item" $item
        done
        ;;
    *)
        echo $msg
        ;;
esac

